# Generated by Django 2.2.4 on 2022-06-25 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_app', '0002_auto_20220625_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date',
            new_name='datehired',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='added_by',
        ),
    ]




class Migration(migrations.Migration):
    atomic = False  # Add atomic
    dependencies = [
        ('apps', '0005_auto_20190701_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date'], 'verbose_name': 'article table', 'verbose_name_plural': 'article table'},
        ),
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
    ]