# Generated by Django 2.2.4 on 2022-06-25 20:54

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False  # Add atomic
    dependencies = [

        ('wishlist_app', '0002_auto_20220625_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date',
            new_name='datehired',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='added_by',
        ),
    ]

